name: Dart (mobile)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Analyze project source
        run: flutter analyze
        working-directory: mobile

      - name: Run tests
        run: flutter test
        working-directory: mobile
